---
# handlers file for keystone

- name: Restart Mariadb Service
  service:
    name: "{{ mariadb_service_name }}"
    state: restarted

- name: Restart Memcached Service
  service:
    name: "{{ memcached_service_name }}"
    state: restarted

- name: Restart Etcd Service
  service:
    name: "{{ etcd_service_name }}"
    state: restarted

- name: Restart http Service
  service:
    name: "{{ http_service_name }}"
    state: restarted



